package ui;

import data.GestorEntidades;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import model.ColaboradorExterno;
import model.GuiaTuristico;
import model.Vehiculo;

/**
 * Formulario visual de NetBeans para registrar entidades de Llanquihue Tour.
 */
public class VentanaRegistro extends javax.swing.JFrame {

    private GestorEntidades gestorEntidades;

    /**
     * Constructor requerido por el editor visual de NetBeans.
     */
    public VentanaRegistro() {
        this(new GestorEntidades());
    }

    public VentanaRegistro(GestorEntidades gestorEntidades) {
        this.gestorEntidades = gestorEntidades;
        initComponents();

        setLocationRelativeTo(null);
        txtResultado.setEditable(false);
        txtResultado.setLineWrap(true);
        txtResultado.setWrapStyleWord(true);
        actualizarEtiquetas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelDatos = new javax.swing.JPanel();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblDatoUno = new javax.swing.JLabel();
        txtDatoUno = new javax.swing.JTextField();
        lblDatoDos = new javax.swing.JLabel();
        txtDatoDos = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jPanelRegistros = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Llanquihue Tour - Registro de entidades");

        jPanelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la entidad"));

        lblTipo.setText("Tipo de entidad");

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guía turístico", "Vehículo", "Colaborador externo" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        lblId.setText("ID");

        lblNombre.setText("Nombre");

        javax.swing.GroupLayout jPanelDatosLayout = new javax.swing.GroupLayout(jPanelDatos);
        jPanelDatos.setLayout(jPanelDatosLayout);
        jPanelDatosLayout.setHorizontalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTipo)
                    .addComponent(lblId)
                    .addComponent(lblNombre)
                    .addComponent(lblDatoUno)
                    .addComponent(lblDatoDos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatoUno, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDatoDos, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDatosLayout.setVerticalGroup(
            jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatoUno)
                    .addComponent(txtDatoUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDatoDos)
                    .addComponent(txtDatoDos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTitulo.setFont(new java.awt.Font("Arial", 0, 28));
        lblTitulo.setText("Sistema Llanquihue Tour");

        btnAgregar.setText("Agregar entidad");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnMostrar.setText("Mostrar registros");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jPanelRegistros.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros de la agencia"));

        txtResultado.setColumns(20);
        txtResultado.setRows(8);
        jScrollPane1.setViewportView(txtResultado);

        javax.swing.GroupLayout jPanelRegistrosLayout = new javax.swing.GroupLayout(jPanelRegistros);
        jPanelRegistros.setLayout(jPanelRegistrosLayout);
        jPanelRegistrosLayout.setHorizontalGroup(
            jPanelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanelRegistrosLayout.setVerticalGroup(
            jPanelRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRegistros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMostrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(lblTitulo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnMostrar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        actualizarEtiquetas();
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregarEntidad();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        mostrarRegistros();
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        confirmarSalida();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void actualizarEtiquetas() {
        String tipo = (String) cmbTipo.getSelectedItem();

        if ("Guía turístico".equals(tipo)) {
            lblDatoUno.setText("Idioma");
            lblDatoDos.setText("Años de experiencia");
        } else if ("Vehículo".equals(tipo)) {
            lblDatoUno.setText("Patente");
            lblDatoDos.setText("Capacidad de pasajeros");
        } else {
            lblDatoUno.setText("Empresa");
            lblDatoDos.setText("Servicio prestado");
        }
    }

    private void agregarEntidad() {
        String tipo = (String) cmbTipo.getSelectedItem();
        String idTexto = txtId.getText().trim();
        String nombre = txtNombre.getText().trim();
        String datoUno = txtDatoUno.getText().trim();
        String datoDos = txtDatoDos.getText().trim();

        if (idTexto.isEmpty() || nombre.isEmpty() || datoUno.isEmpty() || datoDos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
            return;
        }

        int id;
        try {
            id = Integer.parseInt(idTexto);
            if (id <= 0) {
                JOptionPane.showMessageDialog(this, "El ID debe ser mayor que cero.");
                return;
            }
        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número entero válido.");
            return;
        }

        if ("Guía turístico".equals(tipo)) {
            registrarGuia(id, nombre, datoUno, datoDos);
        } else if ("Vehículo".equals(tipo)) {
            registrarVehiculo(id, nombre, datoUno, datoDos);
        } else {
            gestorEntidades.agregarRegistro(new ColaboradorExterno(id, nombre, datoUno, datoDos));
            confirmarRegistro("Colaborador externo agregado correctamente.");
        }
    }

    private void registrarGuia(int id, String nombre, String idioma, String experienciaTexto) {
        try {
            int experiencia = Integer.parseInt(experienciaTexto);
            if (experiencia < 0) {
                JOptionPane.showMessageDialog(this, "La experiencia no puede ser negativa.");
                return;
            }

            gestorEntidades.agregarRegistro(new GuiaTuristico(id, nombre, idioma, experiencia));
            confirmarRegistro("Guía turístico agregado correctamente.");
        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(this, "Los años de experiencia deben ser un número entero válido.");
        }
    }

    private void registrarVehiculo(int id, String nombre, String patente, String capacidadTexto) {
        try {
            int capacidad = Integer.parseInt(capacidadTexto);
            if (capacidad <= 0) {
                JOptionPane.showMessageDialog(this, "La capacidad debe ser mayor que cero.");
                return;
            }

            gestorEntidades.agregarRegistro(new Vehiculo(id, nombre, patente, capacidad));
            confirmarRegistro("Vehículo agregado correctamente.");
        } catch (NumberFormatException excepcion) {
            JOptionPane.showMessageDialog(this, "La capacidad debe ser un número entero válido.");
        }
    }

    private void confirmarRegistro(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
        limpiarCampos();
        actualizarResumen();
    }

    private void mostrarRegistros() {
        String resumen = gestorEntidades.generarResumenRegistros();
        txtResultado.setText(resumen);

        javax.swing.JTextArea areaRegistros = new javax.swing.JTextArea(resumen, 16, 48);
        areaRegistros.setEditable(false);
        areaRegistros.setLineWrap(true);
        areaRegistros.setWrapStyleWord(true);

        javax.swing.JScrollPane panelRegistros = new javax.swing.JScrollPane(areaRegistros);
        panelRegistros.setPreferredSize(new Dimension(560, 360));

        JOptionPane.showMessageDialog(
                this,
                panelRegistros,
                "Registros Llanquihue Tour",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void actualizarResumen() {
        txtResultado.setText(gestorEntidades.generarResumenRegistros());
    }

    private void limpiarCampos() {
        txtId.setText("");
        txtNombre.setText("");
        txtDatoUno.setText("");
        txtDatoDos.setText("");
        txtResultado.setText("");
        txtId.requestFocus();
    }

    private void confirmarSalida() {
        int respuesta = JOptionPane.showConfirmDialog(
                this,
                "¿Desea salir del sistema?",
                "Confirmar salida",
                JOptionPane.YES_NO_OPTION);

        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelRegistros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDatoDos;
    private javax.swing.JLabel lblDatoUno;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDatoDos;
    private javax.swing.JTextField txtDatoUno;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextArea txtResultado;
    // End of variables declaration//GEN-END:variables
}
